### ISSUE TITLE
issue alerts?

### ISSUE THREAD

**Issue by oharac** [eco-detectives/eco_detective#14]
hey all - if you get a notification about this issue in your e-mail, please send a quick response.  Some of us were talking about getting back into Eco Detectives, wrapping up the Bayesian stuff, and moving on to a different book.

**Comment by couture322** [comment]
I didn't get an alert

**Comment by oharac** [comment]
@jcvdav @couture322 @ignacia-rivera @stapial @molwilson testing to see if you get issues when tagged directly

**Comment by molwilson** [comment]
Got the notification when tagged directly! I’ll watch from now on
