### ISSUE TITLE
1st (real) issue

### ISSUE THREAD

**Issue by stapial** [eco-detectives/eco_detective#2]
Hi guys.

So, I was trying to make pseudocode 3.1. I get an output but it's not what I would expect, some probabilities are 612 which is instant nope.

Here's my code

```{r Pseudocode 3.1 Step 3}
probKN <- function (N,p,k){
  p=0.2
  N=50
  k <- seq(1,N,by=1)

  for (i in k) {
  prob = ((N-k+1)/k)*((p)/(1-p))*k[i-1]
  
  }
  return(prob)
}

probKN
```

I'm using the last equation in equation 3.48. As I understand it, the last term is the probability of k-1 (the probability previously calculated). I think that's where my code has a bug since I'm not 100% sure how to do that. 

I sort of tried to do it with the second formula with the additive previous values (! terms). I didn't know how to do that in R either.

Any insight is appreciated.

Thanks!

**Comment by stapial** [comment]
I think I fixed it. I wasn't understanding the problem correctly. I had to calculate p(o,N) as a starting point and then calculate the probability for each following k in the loop using the equation.

Did anyone do something similar?? At least now I get results that make sense (0<p<1)

```{r}
p <- 0.2
N <- 50
```

```{r}
Po <- (1-p)^N
```
#Step 3
```{r Pseudocode 3.1 Step 3}
probKN <- function (N,p,k){
  p=0.2
  N=50
  k <- seq(1,N,by=1)
  p.vec <- vector(length=length(k), "numeric")
  p.vec[1] <- ((N-1+1)/1)*((p)/(1-p))*Po

  for (i in k) {
  p.vec[i+1] = ((N-i+1)/k)*((p)/(1-p))*p.vec[i]
  
  }
  return(p.vec)
}
```

**Comment by oharac** [comment]
Glad you got it working!  were you able to make a plot? bring ‘em tomorrow
to compare with everyone.

I think tomorrow we can chat about loops (the way the pseudocode is set up,
and often more intuitive) and vectorization (more “modern” coding in R and
Matlab, faster and more efficient), also some of the probability short cuts
in R.

**Comment by stapial** [comment]
Thanks! I was able to do a plot.. I just uploaded em, im working on 3.2 and 3.3 now
